AllCops: 
  UseCache: false
  NewCops: enable
Layout/LineLength:
  Max: 874
Lint/UselessRescue:
  Enabled: false
Metrics/AbcSize:
  Max: 537.6
Metrics/BlockLength:
  Max: 292
Metrics/BlockNesting:
  Max: 6
Metrics/ClassLength:
  Max: 134
Metrics/CyclomaticComplexity:
  Max: 157
Metrics/MethodLength:
  Max: 666
Metrics/ModuleLength:
  Max: 1000
Metrics/PerceivedComplexity:
  Max: 156
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: false

inherit_from: .rubocop_todo.yml
