AllCops: 
  UseCache: false
  NewCops: enable
Layout/LineLength:
  Max: 1620
Lint/UselessRescue:
  Enabled: false
Metrics/AbcSize:
  Max: 563.8
Metrics/BlockLength:
  Max: 292
Metrics/BlockNesting:
  Max: 6
Metrics/ClassLength:
  Max: 134
Metrics/CyclomaticComplexity:
  Max: 158
Metrics/MethodLength:
  Max: 565
Metrics/ModuleLength:
  Max: 1447
Metrics/PerceivedComplexity:
  Max: 157
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: false

inherit_from: .rubocop_todo.yml
