inherit_from: .rubocop_todo.yml
AllCops: 
  UseCache: false
  NewCops: enable
Layout:
  Max: 3000
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: false
