AllCops: 
  UseCache: false
  NewCops: enable
Layout/LineLength:
  Max: 293
Lint/UselessRescue:
  Enabled: false
Metrics/AbcSize:
  Max: 537.6
Metrics/BlockLength:
  Max: 220
Metrics/BlockNesting:
  Max: 5
Metrics/ClassLength:
  Max: 134
Metrics/CyclomaticComplexity:
  Max: 123
Metrics/MethodLength:
  Max: 485
Metrics/ModuleLength:
  Max: 1000
Metrics/PerceivedComplexity:
  Max: 122
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: false

inherit_from: .rubocop_todo.yml
